blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/WX7BTs8kwh
    about: Join our Discord server for real-time help and discussions
  - name: ðŸ“š Documentation
    url: https://github.com/tosuapp/tosu/blob/master/README.md
    about: Check out the documentation for guides and information
  - name: ðŸŽ¨ Counters/Overlays
    url: https://github.com/tosuapp/counters/tree/master/counters
    about: Browse available counters and overlays for tosu
